server:
  port: 8090

spring:
  application:
    name: resource-service
  cloud:
    vault:
      scheme: http
      uri: http://127.0.0.1:8200
      authentication: token
      token: hvs.hglQ55cjynUL4KoREE31eN8o
      fail-fast: true
      kv:
        enabled: true
        backend: transit
